### ISSUE TITLE
Use Light Table's standard api whenever possible

### ISSUE THREAD

**Issue by felipebueno** [LightTable/Emacs#18]
Hi.

Why don't we use Light Table's api whenever possible?
eg:
  use
 ```"ctrl-y" [:editor.paste]``` instead of ```"ctrl-y" [(:emacs.keymap-cmd "Ctrl-Y")]```
         ```"alt-w" [:editor.copy]``` instead of ```"alt-w" [(:emacs.keymap-cmd "Alt-W")]```
         ```"ctrl-k" [:editor.kill-line]``` instead of ```"ctrl-k" [(:emacs.keymap-cmd "Ctrl-K")]```
  and so on

I think it would be nice and maybe performance would be better too.

:)

**Comment by Mouvedia** [comment]
@felipebueno Did you find a way to yank?

**Comment by felipebueno** [comment]
Hi, @Mouvedia. I'm not using lighttable anymore. Forget to close this issue... sorry.
